
foundation: Hbar
url: https://justin-hbar.github.io/hosted-landscape2/

colors:
  color1: "rgba(0, 107, 204, 1)"
  color2: "rgba(214, 34, 147, 1)"
  color3: "rgba(96, 149, 214, 1)"
  color4: "rgba(0, 42, 81, 0.7)"
  color5: "rgba(1, 107, 204, 0.7)"
  color6: "rgba(0, 42, 81, 0.7)"
  color7: "rgba(180, 219, 255, 1)"

grid_items_size: large

members_category: Members
groups:
  - name: External Projects
    categories:
      - Enterprise
      - Decentralized Infrastructure
      - Smart Contracts/Tokenization
      #- LF Decentralized Trust Projects
  - name: Hedera Foundation (Funded) Projects
    categories:
      - Defi
      - Enterprise
      - Financial
      - Sustainability
      - Gaming
      #- LF Decentralized Trust Members #left here so we dont have an empty landscape for now
  - name: Hashgraph Association Projects
    categories:
      - Sustainability2
      - Financial2
      - Enterprise2
      - LF Decentralized Trust CSPs #left here so we dont have an empty landscape for now
  
# Footer (optional)
#
# This section allows customizing some aspects of the footer.
#
# footer:
#   links:
#     facebook: <FACEBOOK_URL>
#     flickr: <FLICKR_URL>
#     forums: <FORUMS_URL>
#     github: <GITHUB_URL>
#     homepage: <HOMEPAGE_URL>
#     instagram: <INSTAGRAM_URL>
#     linkedin: <LINKEDIN_URL>
#     slack: <SLACK_URL>
#     twitch: <TWITCH_URL>
#     twitter: <TWITTER_URL>
#     wechat: <WECHAT_URL>
#     youtube: <YOUTUBE_URL>
#   logo: <LOGO_URL>  # Foundation logo featured on the footer
#   text: <TEXT>      # Copyright notice, for example
#
footer:
  links:
    github: "https://github.com/hbar-inc"
    homepage: "https://hedera.foundation"
    #linkedin: "https://www.linkedin.com/company/cloud-native-computing-foundation/"
    #twitter: "https://twitter.com/cloudnativefdn"
    #youtube: "https://www.youtube.com/c/cloudnativefdn"
  logo: "https://optimistic-happiness-a3dab1f6d6.media.strapiapp.com/logo_w288px_d59a8a366a.svg"
  text: |
    Copyright © 2024 The Linux Foundation®. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage page](https://www.linuxfoundation.org/trademark-usage). Linux is a registered trademark of Linus Torvalds. [Privacy Policy](https://www.linuxfoundation.org/privacy) and [Terms of Use](https://www.linuxfoundation.org/terms). This website contains data received from Crunchbase. This data is not licensed pursuant to the Apache License. It is subject to Crunchbase's Data Access Terms, available at <https://data.crunchbase.com/docs/terms>, and is only permitted to be used with Linux Foundation landscape projects.
